### ISSUE TITLE
Declaration of JonnyW\PhantomJs\DependencyInjection\ServiceContainer::load()

### ISSUE THREAD

**Issue by georgemiler** [michaeluno/php-simple-web-scraper#1]
Issue

Warning: Declaration of JonnyW\PhantomJs\DependencyInjection\ServiceContainer::load() should be compatible with Symfony\Component\DependencyInjection\Container::load($file) in   : php-simple-web-scraper\vendor\jonnyw\php-phantomjs\src\JonnyW\PhantomJs\DependencyInjection\ServiceContainer.php on line 20

Fatal error: Uncaught Error: Call to undefined method JonnyW\PhantomJs\Http\Request::addSetting() in  php-simple-web-scraper\web\include\class\Browser\Browser.php on line 17

**Comment by michaeluno** [comment]
According to the upstream library [issue](https://github.com/jonnnnyw/php-phantomjs/issues/259), you need the PHP [Bzip2](https://www.php.net/manual/en/bzip2.installation.php) extension installed.

**Comment by buzz8year** [comment]
It is actually php version & psr related problem of mentioned dependency package, solution is [already](https://github.com/jonnnnyw/php-phantomjs/pull/235) merged.
