### ISSUE TITLE
Javascript content show issue 

### ISSUE THREAD

**Issue by ghost** [michaeluno/php-simple-web-scraper#3]
Hi, by using heroku i am deployed the app, and it works like a fire their and tried to get the javascript content of the web page, and exactly what i needed i got it , but the same thing i tried in Windows server 2019, everything installed without any issues including phantomJs also.
When i try to crawl the same web page here, i am not getting javascript content what i got in heroku.

Can i know what is the possible reason for this ?
PhantomJs bin path:
http://3.134.82.150/crowl/vendor/bin/phantomjs.exe
Here the details of links what i am used
Heroku link:
https://pcrawl.herokuapp.com/
Or try at yours web page
https://php-simple-web-scraper.herokuapp.com/

Windows link:
http://3.134.82.150/crowl/web/
Crawl link:
http://3.134.82.150/d_a.php

**Comment by michaeluno** [comment]
I don't understand your problem.  Maybe try setting a user-agent.

And post error messages you got and possibly with some screenshots.

**Comment by ghost** [comment]
Please follow this steps to reproduce the issue

First copy the this crawl link 
http://3.134.82.150/d_a.php

Then go and paste it here to crawl
https://pcrawl.herokuapp.com/
Here what iam needed  i getting

Then next use the same crawl link at here
http://3.134.82.150/crowl/web/

Here i am not getting any response

That's the issue.

Iam not getting any errors from php, but the javascript content is not loading here

**Comment by ghost** [comment]
Please check this video clip 

https://user-images.githubusercontent.com/36628081/122795491-021c1e00-d2db-11eb-8e01-7bd691c0e12f.mp4

**Comment by michaeluno** [comment]
When trying http://3.134.82.150/d_a.php with http://3.134.82.150/crowl/web/, a malformed HTML source code can be seen.

Can you upload the following HTML file to the sever 3.134.82.150 and make it accessible through browsers? Name the file test.html to let it run a plain HTML. Do not use PHP in this test.

```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Test</title>
  <script>
      function setText( id, text ) {
          var theDiv = document.getElementById( id, text );
          theDiv.innerHTML = text;
      }
  </script>
</head>
<body onload='setText("test", "Hi, there." )'>
  <h2>Test</h2>
  <noscript><p>No Script Content.</p></noscript>
  <p id="test">Unchanged.</p>
</body>
</html>
```

**Comment by ghost** [comment]
Please check out this link
http://3.134.82.150/crowl/web/test.html
As per your suggestion i did

**Comment by michaeluno** [comment]
It looks good. http://3.134.82.150/crowl/web/?url=http%3A%2F%2F3.134.82.150%2Fcrowl%2Fweb%2Ftest.html&output=screenshot If the JavaScript script is not working, a different message will be displayed. 

![image](https://user-images.githubusercontent.com/3408158/122847823-5824ac00-d343-11eb-9835-53f043acc2da.png)

So try fix the malformed HTML mark ups in your `d_a.php` by giving proper html tags.

**Comment by ghost** [comment]
Here thing is not javascript content malform.

In heroku the app is waiting to load and execution of  javascript then it
gives the output.

But here without finishing of javascript execution it giving response.
It's the main issue.


I think phantomJs is not working properly here

**Comment by ghost** [comment]
http://3.134.82.150/d_a.php
This is a javascript event based script.
When the page loads then event will be fired, after the event fire request will be sent to server, their iam used `apache_headers()` to get Headers from request to show in webpage.

As per my knowledge something is wrong with phantomJs.

If possible please try with any window platform. So you may get better details

**Comment by ghost** [comment]
Rather then heroku, please deploy the app some others platform like in windows or linux and try to crawl js webpage(nodejs webapps not at all able to crawl), maybe that time you may getting proper details about the issue.

**Comment by michaeluno** [comment]
I cannot reproduce the issue described in your last reply. 

Are you running node.js and PHP on the same server?

**Comment by ghost** [comment]
No iam running apache and nginx servers.

I just want to know what's the root cause .

i am pretty sure that html is not malformed.

**Comment by michaeluno** [comment]
It could be a timeout issue.

**Comment by j311yfish** [comment]
So where i can set that settings?

**Comment by j311yfish** [comment]
Even after making changes of timeout and delay then also problem not solved :(

**Comment by ghost** [comment]
Thanks you so much for your precious reply

**Comment by ghost** [comment]
As per your suggestion, now i did delay settings and now it working fine
